Config:
  # Edit mode?
  EditMode: false
  # Should we use NMS? WARNING: This may cause problems with mismatched versions,
  # (i.e. EquestrianDash 1.7.9 used with a later version of Bukkit/Spigot)
  NMS:
    Enabled: true
    MaxHorseSpeed: 0.225
  # All raceline settings.
  Raceline:
    # Where should the first corner of the raceline be?
    Lap1:
      X: 0
      Y: 0
      Z: 0
    # Where should the second corner of the raceline be?
    Lap2:
      X: 0
      Y: 0
      Z: 0
  # These are the player settings.
  Players:
    # Minimum players to start a game.
    Min: 2
    # Maximum players allowed at a time.
    Max: 8
  # From where should the firework launch?
  Fw:
    X: 0
    Y: 0
    Z: 0
  # From where should the screen count down from before the game begins?
  Countdown: 30
  # How many laps does this level have?
  Laps: 3
  # Editor settings.
  Editor:
    # How many markers does this level have? (IMPORTANT!)
    Markers: 0
  # Powerup config.
  Powerups:
    Launcher:
      Enabled: true # Should this be used as a default powerup?
      Title: '&b&lLauncher Powerup' # The powerup's name (will shop up in the item's title)
      Material: 'DIAMOND' # The material for the powerup. Full list of Materials: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
      Chance: 2 # The amount of times the powerup is entered into the powerup chooser. Higher = less frequent. For math nerds: Frequency = rank / chance.
    Speed:
      Enabled: true
      Title: '&f&lSpeed Powerup'
      Material: 'SUGAR'
      Chance: 3
      Length: 100 # NOTE: Length is in ticks. 20 ticks = 1 second.
      Amplifier: 4 # i.e "2" would be the equivelant to "Speed II"
    TNT:
      Enabled: true
      Title: '&c&lTNT Powerup'
      Material: 'TNT'
      Chance: 2
      ThrowDirections:
        ThrowAheadEnabled: true
        ThrowAheadTicks: 60
        ThrowAheadMultiplier: 2.5
        ThrowBehindEnabled: true
        ThrowBehindTicks: 40
    Slime:
      Enabled: true
      Title: '&a&lSlime Minions Powerup'
      Material: 'SLIME_BALL'
      Chance: 1
    Arrow:
      Enabled: true
      Title: '&9&lArrow Powerup'
      Material: 'ARROW'
      Chance: 4
  # The following are spawnpoint location settings.
  Spawn1:
    X: 0
    Y: 0
    Z: 0
  Spawn2:
    X: 0
    Y: 0
    Z: 0
  Spawn3:
    X: 0
    Y: 0
    Z: 0
  Spawn4:
    X: 0
    Y: 0
    Z: 0
  Spawn5:
    X: 0
    Y: 0
    Z: 0
  Spawn6:
    X: 0
    Y: 0
    Z: 0
  Spawn7:
    X: 0
    Y: 0
    Z: 0
  Spawn8:
    X: 0
    Y: 0
    Z: 0