name: EquestrianDash
main: com.ColonelHedgehog.Dash.Core.EquestrianDash
version: 0.9
author: TheHandfish
softdepend: [Multiverse-Core, TitleManager]
load: POSTWORLD
commands:
  ed:
    description: ED Base Command. Do /ed help for help.
    permission: equestriandash.ed
    permission-message: 'ยง4Error: ยง6Insufficient permissions.'
  vote:
    description: Vote for the map.
    permission: equestriandash.vote
    permission-message: 'ยง4Error: ยง6Insufficient permissions.'