name: Equestrian Dash
main: com.hand.Race.Main
version: 1.0
author: TheHandfish
commands:
  edspawn:
    description: Use this command to designate certain spawn points.
    usage: /edspawn (spawn[1-8], flarespawn)
    permission: EquestrianDash.SetSpawns
    permission-message: ยง4Error; ยง6Insufficient permissions.
